//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeraBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bank : DbContext
    {
        public Bank()
            : base("name=Bank")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_AccountBalance> tbl_AccountBalance { get; set; }
        public DbSet<tbl_AccountHolder> tbl_AccountHolder { get; set; }
        public DbSet<tbl_TranferDetails> tbl_TranferDetails { get; set; }
    }
}
