//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeraBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountHolder
    {
        public tbl_AccountHolder()
        {
            this.tbl_AccountBalance = new HashSet<tbl_AccountBalance>();
            this.tbl_TranferDetails = new HashSet<tbl_TranferDetails>();
        }
    
        public int ActId { get; set; }
        public string ActName { get; set; }
        public string ActFather { get; set; }
        public string CNIC { get; set; }
        public string ActMobile { get; set; }
        public string ActEmail { get; set; }
        public string ActGender { get; set; }
        public string ActStatus { get; set; }
        public string ActAdress { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<tbl_AccountBalance> tbl_AccountBalance { get; set; }
        public virtual ICollection<tbl_TranferDetails> tbl_TranferDetails { get; set; }
    }
}
